language: node_js
node_js:
- 4.2.1
sudo: false
deploy:
  provider: npm
  email: sysadmin@coreybutler.com
  api_key:
    secure: RBu2QLzpXycIaoOL7A2iPATGCMW2RE8CUcHyFIUEusTH5qCaWMWGGc6/gAXnbf1AogsPHZHpT0sOxG+/HBmpgHD7thROyaQ63mrp96pcZTMlnX+DvAPhZiicTs6GZ1bAia/2niE24UfpnY51nIQbsRBXtRXCvyaRdneaxw/6TzXBqkNZem/oJ9hGimi9uVAdEAAhMLIhoOKSrtqWwXaOxEoPyzImoZszgbOT3SbR3DV1CrT8vN0HKGWnT/11wUrgC6l4YdNcIeh3d8v3mTiJcSG52GvC/wY7xrB29f5BqjCnbNQ4OGwePr2GJyX9ZfBpeg5vCN1Ed/Wx92NK2J8c2ZEwYjIzqdSDRHHuOgefoOjtf6DXxXuY5bHvgeBnB8MPfz5x0UvpQ+GdEoL5A7ESgStiv7tGu19Q18++rRK+Qm7ySfkC8VaRkiWLWJcFXIwI/14CwFItmMkbeedIIC2Dty6fSjkaC2NwW/A0nf+n18mG4uhTYuNEhJXKj7+Xb02J/9SVelds3pI7qMWmVogBHq2e4TmFxY8voMdksM0jgC5N9BSFW4fNnQzSmn8wEH4Ke1zcs4aZDTYqXEEv43Lj3/lKh026DwEX7xr4LJoZRQWoDr2hVrRMFG5ml+7hf6kHdJCFcmNnZe/IheMUOEHow3pxVTi62oNmt33e4z6izTM=
  on:
    tags: true
cache:
  directories:
  - node_modules
notifications:
  hipchat:
    rooms:
      secure: 2pNODDUgtRXYvnivkgVjBQLxP+HDimanKKMH4gO/vatswhlP1TKDDgGruh8aLkIEK6vI3z0HmlPti6abgAeZeBjhUKCQEZjw1D75N0GHnThjlgFJIN089lgKIjuAZCkLakNv+xNoOJgZ+0r/ee6C0qxg0g5lk+SKHfNDn71Q1mDfxBpOg3TCyC04aXmeySzFtHv459+sGThqVLce4u731n/K1hFilExkqr1QZ4kgBf1BUtF4cmidIC2ViQvCR8viEvtBrSu3OYElzMItOeFb0dLi1GlFWAR/ydXcsJO42LVd3ylVTvG+q+5Ls2BuSfcwhWe3JNG0BG+f7YnPOnFItft14Zdbi2P9oo3/DIe2FyBYy3jm8C36omRWDm34sKEQZWOvfGjPr7ZxfoIrbjOd+VZMmhevqwmaLFwQwzK6TLRqjY3tT4XiqUNKSP8lgPysLpIy9q+P1HZL+62AhM67Sxk3Vpxw4NvIggbPcQtTsbOml0KWjTeA1Zak2NTv/yBRSHIGQTqhl3Qh0YuzrnHOXrJD5cNHFWAeTTZt1UL/SGhqEoK/5hVbjs0HQfRprBPxyqRr1Zv8z0RzihHS05A2ehBfBhdY5SE6N662p9ePWh4M3aF98mwTkqWxcg/aIfYEpjPZn/xUU3+LRE0x28jcOeu7HgA+5mWI3MFXflnG0jg=
